AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    airbud

    Simple lambda function for the air table api
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 30

Parameters:
    AirtableApiUrl:
        Type: String
    AirtableTable:
        Type: String
    AirtableApiKey:
        Type: String
    AirtableFilter:
        Type: String
    ZenchetteApiUrl:
        Type: String

Resources:
    AirBudFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: airbud/build/
            Handler: app.lambda_handler
            Runtime: python3.6
            Environment:
                Variables:
                    AIRTABLE_TABLE: !Ref AirtableTable
                    AIRTABLE_API_URL: !Ref AirtableApiUrl
                    AIRTABLE_API_KEY: !Ref AirtableApiKey
                    AIRTABLE_FILTER: !Ref AirtableFilter
                    ZENCHETTE_API_URL: !Ref ZenchetteApiUrl
            Events:
                UpdateRequestApiEvent:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /
                        Method: ANY
                AutoUpdateScheduledEvent:
                    Type: Schedule
                    Properties:
                        Schedule: cron(*/15 8-18 * * 1-5 *)


Outputs:
    AirBudApi:
      Description: "API Gateway endpoint URL for Prod stage for airbud function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/airbud/"
    AirBudFunction:
      Description: "AirBud Lambda Function ARN"
      Value: !GetAtt AirBudFunction.Arn
    AirBudFunctionIamRole:
      Description: "Implicit IAM Role created for AirBud function"
      Value: !GetAtt AirBudFunctionRole.Arn
